import type { TemplateMeta } from './types';

function createThumbnail(category: string, intensity: string): string {
  const colors: Record<string, string> = {
    essential: '0cc',
    professional: '08f',
    creative: 'f0c',
    technical: '0f0',
    social: '0cf',
  };
  const color = colors[category] || '0cc';
  return `data:image/svg+xml,${encodeURIComponent(`
    <svg xmlns="http://www.w3.org/2000/svg" width="300" height="200" viewBox="0 0 300 200">
      <rect width="300" height="200" fill="#${color}0d"/>
      <text x="150" y="100" font-family="system-ui" font-size="14" fill="#${color}" text-anchor="middle" dominant-baseline="middle">${category} • ${intensity}</text>
    </svg>
  `)}`;
}

export const TEMPLATE_REGISTRY: TemplateMeta[] = [
  // ESSENTIAL LINE (Whitespace → Content)
  {
    id: 'essential-minimal',
    name: 'Clean Slate',
    category: 'essential',
    intensity: 'minimal',
    preset: 'minimal',
    description: 'Single column, centered, 640px max. Pure content focus.',
    tags: ['minimal', 'clean', 'students', 'resume'],
    thumbnail: createThumbnail('essential', 'minimal'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 10,
      maxProofPoints: 3,
    },
  },
  {
    id: 'essential-light',
    name: 'Breathing Room',
    category: 'essential',
    intensity: 'light',
    preset: 'minimal',
    description: 'Subtle divider lines between sections.',
    tags: ['minimal', 'dividers', 'portfolio'],
    thumbnail: createThumbnail('essential', 'light'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 12,
      maxProofPoints: 4,
    },
  },
  {
    id: 'essential-standard',
    name: 'Balanced',
    category: 'essential',
    intensity: 'standard',
    preset: 'minimal',
    description: 'Avatar ring, bio card, link hover effects.',
    tags: ['standard', 'bio-card', 'general'],
    thumbnail: createThumbnail('essential', 'standard'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 5,
    },
  },
  {
    id: 'essential-bold',
    name: 'Statement',
    category: 'essential',
    intensity: 'bold',
    preset: 'bold',
    description: 'Thick accent bar top, Purple accent, Mono links.',
    tags: ['bold', 'accent-bar', 'personal-brand'],
    thumbnail: createThumbnail('essential', 'bold'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: true,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 6,
    },
  },
  {
    id: 'essential-max',
    name: 'Bold Canvas',
    category: 'essential',
    intensity: 'max',
    preset: 'bold',
    description: 'Full-bleed background glow with orbital orbs.',
    tags: ['max', 'orbital', 'high-impact'],
    thumbnail: createThumbnail('essential', 'max'),
    features: {
      has3DBackground: true,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 8,
    },
  },

  // PROFESSIONAL LINE (Structure → Authority)
  {
    id: 'professional-minimal',
    name: 'Executive',
    category: 'professional',
    intensity: 'minimal',
    preset: 'corporate',
    description: 'Two-column: info | links. Blue accent, clean structure.',
    tags: ['executive', 'two-column', 'consultants'],
    thumbnail: createThumbnail('professional', 'minimal'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 12,
      maxProofPoints: 4,
    },
  },
  {
    id: 'professional-light',
    name: 'Structured',
    category: 'professional',
    intensity: 'light',
    preset: 'corporate',
    description: 'Company badge row with logos.',
    tags: ['badges', 'company-logos', 'agencies'],
    thumbnail: createThumbnail('professional', 'light'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 5,
    },
  },
  {
    id: 'professional-standard',
    name: 'Founder',
    category: 'professional',
    intensity: 'standard',
    preset: 'corporate',
    description: 'Metrics strip (3 KPIs) with tilt cards.',
    tags: ['metrics', 'kpis', 'founders'],
    thumbnail: createThumbnail('professional', 'standard'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: true,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 6,
    },
  },
  {
    id: 'professional-bold',
    name: 'Authority',
    category: 'professional',
    intensity: 'bold',
    preset: 'corporate',
    description: 'Testimonial carousel with perspective flip.',
    tags: ['testimonials', 'carousel', 'speakers'],
    thumbnail: createThumbnail('professional', 'bold'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 8,
    },
  },
  {
    id: 'professional-max',
    name: 'Command',
    category: 'professional',
    intensity: 'max',
    preset: 'corporate',
    description: 'Full dashboard layout with sidebar navigation.',
    tags: ['dashboard', 'sidebar', 'enterprise'],
    thumbnail: createThumbnail('professional', 'max'),
    features: {
      has3DBackground: true,
      hasParallax: false,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: false,
      maxLinks: 25,
      maxProofPoints: 10,
    },
  },

  // CREATIVE LINE (Expression → Personality)
  {
    id: 'creative-minimal',
    name: 'Whitespace',
    category: 'creative',
    intensity: 'minimal',
    preset: 'creative',
    description: 'Asymmetric grid, generous gaps, Syne display font.',
    tags: ['asymmetric', 'grid', 'writers'],
    thumbnail: createThumbnail('creative', 'minimal'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 10,
      maxProofPoints: 3,
    },
  },
  {
    id: 'creative-light',
    name: 'Flow',
    category: 'creative',
    intensity: 'light',
    preset: 'creative',
    description: 'Floating blobs background with orbital motion.',
    tags: ['blobs', 'orbital', 'illustrators'],
    thumbnail: createThumbnail('creative', 'light'),
    features: {
      has3DBackground: true,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: true,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 12,
      maxProofPoints: 4,
    },
  },
  {
    id: 'creative-standard',
    name: 'Expressive',
    category: 'creative',
    intensity: 'standard',
    preset: 'creative',
    description: 'Animated gradient text on name, purple accent.',
    tags: ['gradient-text', 'animated', 'designers'],
    thumbnail: createThumbnail('creative', 'standard'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: false,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 6,
    },
  },
  {
    id: 'creative-bold',
    name: 'Dramatic',
    category: 'creative',
    intensity: 'bold',
    preset: 'creative',
    description: '3D tilt cards on hover for links, purple theme.',
    tags: ['tilt', '3d', 'dramatic', 'agencies'],
    thumbnail: createThumbnail('creative', 'bold'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 8,
    },
  },
  {
    id: 'creative-max',
    name: 'Immersive',
    category: 'creative',
    intensity: 'max',
    preset: 'creative',
    description: 'Full immersive: parallax layers, video background support.',
    tags: ['immersive', 'parallax', 'video', 'portfolios'],
    thumbnail: createThumbnail('creative', 'max'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: true,
      maxLinks: 25,
      maxProofPoints: 10,
    },
  },

  // TECHNICAL LINE (Code → Data)
  {
    id: 'technical-minimal',
    name: 'Terminal',
    category: 'technical',
    intensity: 'minimal',
    preset: 'technical',
    description: 'Terminal header, monospace throughout, green accent.',
    tags: ['terminal', 'monospace', 'developers'],
    thumbnail: createThumbnail('technical', 'minimal'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 5,
    },
  },
  {
    id: 'technical-light',
    name: 'REPL',
    category: 'technical',
    intensity: 'light',
    preset: 'technical',
    description: 'Syntax-highlighted bio block with Prism-like colors.',
    tags: ['syntax-highlight', 'code', 'engineers'],
    thumbnail: createThumbnail('technical', 'light'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 15,
      maxProofPoints: 6,
    },
  },
  {
    id: 'technical-standard',
    name: 'IDE',
    category: 'technical',
    intensity: 'standard',
    preset: 'technical',
    description: 'GitHub stats cards (repos, stars, forks) with tilt.',
    tags: ['github', 'stats', 'oss-maintainers'],
    thumbnail: createThumbnail('technical', 'standard'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: true,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 8,
    },
  },
  {
    id: 'technical-bold',
    name: 'Dashboard',
    category: 'technical',
    intensity: 'bold',
    preset: 'technical',
    description: 'Live commit ticker animation (morphing blob style).',
    tags: ['ticker', 'live', 'tech-leads'],
    thumbnail: createThumbnail('technical', 'bold'),
    features: {
      has3DBackground: true,
      hasParallax: false,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 8,
    },
  },
  {
    id: 'technical-max',
    name: 'Mission Control',
    category: 'technical',
    intensity: 'max',
    preset: 'technical',
    description: 'Full IDE layout: file tree sidebar, editor main, terminal bottom.',
    tags: ['ide', 'file-tree', 'terminal', 'dev-advocates'],
    thumbnail: createThumbnail('technical', 'max'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: false,
      maxLinks: 30,
      maxProofPoints: 12,
    },
  },

  // SOCIAL LINE (Feed → Engagement)
  {
    id: 'social-minimal',
    name: 'Links Only',
    category: 'social',
    intensity: 'minimal',
    preset: 'minimal',
    description: 'Link pills centered, pure link-in-bio style.',
    tags: ['pills', 'link-in-bio', 'minimal'],
    thumbnail: createThumbnail('social', 'minimal'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 2,
    },
  },
  {
    id: 'social-light',
    name: 'Connect',
    category: 'social',
    intensity: 'light',
    preset: 'minimal',
    description: 'Avatar stack followers with ring-pulse animation.',
    tags: ['avatar-stack', 'followers', 'micro-influencers'],
    thumbnail: createThumbnail('social', 'light'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: false,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 20,
      maxProofPoints: 3,
    },
  },
  {
    id: 'social-standard',
    name: 'Feed',
    category: 'social',
    intensity: 'standard',
    preset: 'creative',
    description: 'Feed cards with thumbnails, magnetic hover.',
    tags: ['feed', 'thumbnails', 'creators'],
    thumbnail: createThumbnail('social', 'standard'),
    features: {
      has3DBackground: false,
      hasParallax: false,
      hasTiltCards: false,
      hasMagneticHover: true,
      hasAnimatedOrbs: false,
      hasGradientText: false,
      supportsVideoBackground: false,
      maxLinks: 25,
      maxProofPoints: 5,
    },
  },
  {
    id: 'social-bold',
    name: 'Engage',
    category: 'social',
    intensity: 'bold',
    preset: 'creative',
    description: 'Engagement rings (animated) on avatars, Syne display.',
    tags: ['engagement-rings', 'animated', 'creators'],
    thumbnail: createThumbnail('social', 'bold'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: false,
      maxLinks: 30,
      maxProofPoints: 8,
    },
  },
  {
    id: 'social-max',
    name: 'Universe',
    category: 'social',
    intensity: 'max',
    preset: 'creative',
    description: 'Full mini-feed: posts, replies, media, infinite scroll feel.',
    tags: ['feed', 'posts', 'replies', 'power-users'],
    thumbnail: createThumbnail('social', 'max'),
    features: {
      has3DBackground: true,
      hasParallax: true,
      hasTiltCards: true,
      hasMagneticHover: true,
      hasAnimatedOrbs: true,
      hasGradientText: true,
      supportsVideoBackground: true,
      maxLinks: 40,
      maxProofPoints: 12,
    },
  },
];

export function getTemplateById(id: string): TemplateMeta | undefined {
  return TEMPLATE_REGISTRY.find(t => t.id === id);
}

export function getTemplatesByCategory(category: TemplateMeta['category']): TemplateMeta[] {
  return TEMPLATE_REGISTRY.filter(t => t.category === category);
}

export function getTemplatesByIntensity(intensity: TemplateMeta['intensity']): TemplateMeta[] {
  return TEMPLATE_REGISTRY.filter(t => t.intensity === intensity);
}

export function getDefaultTemplate(category: TemplateMeta['category'] = 'essential'): TemplateMeta {
  return TEMPLATE_REGISTRY.find(t => t.category === category && t.intensity === 'standard')!;
}